### ISSUE TITLE
Thomas Leeper (@thosjleeper) December 24, 2015

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/datacheckr#1]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/joe_thorley">@joe_thorley</a> Sounds somewhat similar to <a href="https://t.co/22yejGe9EJ">https://t.co/22yejGe9EJ</a> and <a href="https://t.co/9g2IZvr3KD">https://t.co/9g2IZvr3KD</a></p>&mdash; Thomas Leeper (@thosjleeper) <a href="https://twitter.com/thosjleeper/status/680117151689248768">December 24, 2015</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by joethorley** [comment]
Hi Thomas

They are similar. 

I use and like `assertr` alot. Its great for tests in scripts. 

However its error messages are 
somewhat cryptic particularly when embedded in functions in packages. Consider the following:

```
library(assertr)
library(magrittr)
mtcars %>% verify(nrow(.) > 1000)
```

The error is `Error in verify(., nrow(.) > 1000) : verification failed! (1 failure)` which is not that helpful for a user who is not familiar with the internals of a function that has just thrown that error.

Also consider the example deckr code

```
deck(df, list("Count" = c(0L, .Machine$integer.max), 
  "Comments" = NULL, 
   "LocationX" = c(NA, 2345, 1012),
   "LocationX" = NULL))
```

it states that `df` should have column `Count` of non-missing counts, should not have a column `Comments` and can include a column `LocationX` with missing values between 1012 and 2345.

To produce similar functionality with assertr would require something like

```
stopifnot(!"Comments" %in% colnames(df))
df %<>% verify(Count > 0) 
if("LocationX" %in% colnames(df))
  df %<>% assert(within_bounds(1012, 2345), LocationX)
```

which is the same number of lines but less readable.

Finally to repeat the tests on several data frames could be done very efficiently using deck

```
values <- list("Count" = c(0L, .Machine$integer.max), 
  "Comments" = NULL, 
   "LocationX" = c(NA, 2345, 1012),
   "LocationX" = NULL)

deck(df, values)
deck(df2, values)
deck(df3, values)
```

The same code using `assertr` would require 

```
stopifnot(!"Comments" %in% colnames(df))
df %>% verify(Count > 0) 
if("LocationX" %in% colnames(df))
  df %<>% assert(within_bounds(1012, 2345), LocationX)

stopifnot(!"Comments" %in% colnames(df2))
df2 %<>% verify(Count > 0) 
if("LocationX" %in% colnames(df2))
  df2 %<> %assert(within_bounds(1012, 2345), LocationX)

stopifnot(!"Comments" %in% colnames(df3))
df3 %<>% verify(Count > 0) 
if("LocationX" %in% colnames(df3))
  df3 %<> %assert(within_bounds(1012, 2345), LocationX)
```

which is tedious to produce and read and as a result error prone.

The `assertive` package seems to be a collection of `is` and `has` functions.

**Comment by joethorley** [comment]
Note the error messages with `assertr` are of course more informative if not in a pipeline

```
verify(mtcars, nrow(mtcars) > 1000)
```

produces

```
Error in verify(mtcars, nrow(mtcars) > 1000) :  verification failed! (1 failure)
```

**Comment by leeper** [comment]
Nice discussion. I would consider adding some of this to the README to put the package in context.

**Comment by joethorley** [comment]
@leeper done
