### ISSUE TITLE
Any specific reason for dependency on R >= 3.2.3 ?

### ISSUE THREAD

**Issue by UweBlock** [poissonconsulting/datacheckr#5]
Congrats! This package seems to be a valuable companion to assertive, assertthat, assertr and the like when it comes to checking the contents, ie, the columns of data.frame and data.table parameters passed to functions. I always felt that something was missing for this purpose.

However, I wonder if the dependency on R version 3.2.3 is a real requirement. I'm using R & RStudio on a server which always lags behind the latest R version updates and therefore doesn't allow installation of datacheckr.

Thank you for looking into this.
Brgds,
Uwe

**Comment by joethorley** [comment]
Thanks!

Its likely not a real requirement. datacheckr has no dependencies and uses relatively simple base functions. Unfortunately testing a package on earlier versions of R appears to be painful and time-consuming... 

If you want to use datacheckr on an earlier version of R one option would me to fork the package and remove the dependency in the description file and then install that version. If it passes all tests it should be good to go.

I hope this helps

Joe

**Comment by UweBlock** [comment]
Dear Joe,

thanks for your reply. I will follow your advise and try to fork the package. 

I understand that testing (and releasing a package) for different R versions is tedious.
However, would it be possible to specificy the dependency on a minor R release, ie, 3.2 oder 3.2.0 rather than a specific patch level like 3.2.3? 

Brgds,
Uwe

**Comment by joethorley** [comment]
Done - the development version now only requires that R (>= 3.2.0).

I'll pass this thru to version 0.0.3 when I submit to CRAN (this may be several months or more in the future)
